<?php

/**
 * Checkout.com Apiservices\Charges\Requestmodels\Basechargeinfo.
 *
 * PHP Version 5.6
 *
 * @category Api Services
 * @package Checkoutapi
 * @license https://checkout.com/terms/ MIT License
 * @link https://www.checkout.com/
 */

namespace com\checkout\Apiservices\Charges\Requestmodels;

/**
 * Class Basecharge Info.
 *
 * @category Api Services
 * @version Release: @package_version@
 */
class Basechargeinfo extends \com\checkout\Apiservices\Sharedmodels\Basehttp {
  protected $description;
  protected $trackId;
  protected $udf1;
  protected $udf2;
  protected $udf3;
  protected $udf4;
  protected $udf5;
  protected $metadata = array();
  protected $descriptor;

  /**
   * Get a description that can be added to this object.
   *
   * @return mixed
   *   The description.
   */
  public function getDescription() {
    return $this->description;
  }

  /**
   * Set a description that can be added to this object.
   *
   * @param mixed $description
   *   The description.
   */
  public function setDescription($description) {
    $this->description = $description;
  }

  /**
   * Get a track id.
   *
   * Order tracking id generated by the merchant. Max length 50 characters.
   *
   * @return mixed
   *   The trackId.
   */
  public function getTrackId() {
    return $this->trackId;
  }

  /**
   * Set a track id.
   *
   * Order tracking id generated by the merchant. Max length 50 characters.
   *
   * @param mixed $trackId
   *   The trackId.
   */
  public function setTrackId($trackId) {
    $this->trackId = $trackId;
  }

  /**
   * Get the user defined field 1.
   *
   * User defined field 1, max. 100 characters
   *
   * @return mixed
   *   The udf1.
   */
  public function getUdf1() {
    return $this->udf1;
  }

  /**
   * Set the user defined field 1.
   *
   * User defined field 1, max. 100 characters
   *
   * @param mixed $udf1
   *   The udf1.
   */
  public function setUdf1($udf1) {
    $this->udf1 = $udf1;
  }

  /**
   * Get the user defined field 2.
   *
   * User defined field 2, max. 100 characters
   *
   * @return mixed
   *   The udf2.
   */
  public function getUdf2() {
    return $this->udf2;
  }

  /**
   * Set the user defined field 2.
   *
   * User defined field 2, max. 100 characters
   *
   * @param mixed $udf2
   *   The udf2.
   */
  public function setUdf2($udf2) {
    $this->udf2 = $udf2;
  }

  /**
   * Get the user defined field 3.
   *
   * User defined field 3, max. 100 characters
   *
   * @return mixed
   *   The udf3.
   */
  public function getUdf3() {
    return $this->udf3;
  }

  /**
   * Set the user defined field 3.
   *
   * User defined field 3, max. 100 characters
   *
   * @param mixed $udf3
   *   The udf3.
   */
  public function setUdf3($udf3) {
    $this->udf3 = $udf3;
  }

  /**
   * Get the user defined field 4.
   *
   * User defined field 4, max. 100 characters
   *
   * @return mixed
   *   The udf4.
   */
  public function getUdf4() {
    return $this->udf4;
  }

  /**
   * Set the user defined field 4.
   *
   * User defined field 4, max. 100 characters
   *
   * @param mixed $udf4
   *   The udf4.
   */
  public function setUdf4($udf4) {
    $this->udf4 = $udf4;
  }

  /**
   * Get the user defined field 5.
   *
   * User defined field 5, max. 100 characters
   *
   * @return mixed
   *   The udf5.
   */
  public function getUdf5() {
    return $this->udf5;
  }

  /**
   * Set the user defined field 5.
   *
   * User defined field 5, max. 100 characters
   *
   * @param mixed $udf5
   *   The udf5.
   */
  public function setUdf5($udf5) {
    $this->udf5 = $udf5;
  }

  /**
   * Get a hash of FieldName and value pairs.
   *
   * A hash of FieldName and value pairs e.g. {'keys1': 'Value1'}.
   * Max length of key(s) and value(s) is 100 each. A max. of 10 KVP are allowed.
   *
   * @return mixed
   *   The metadata.
   */
  public function getMetadata() {
    return $this->metadata;
  }

  /**
   * Set a hash of FieldName and value pairs.
   *
   * A hash of FieldName and value pairs e.g. {'keys1': 'Value1'}.
   * Max length of key(s) and value(s) is 100 each. A max. of 10 KVP are allowed.
   *
   * @param mixed $metadata
   *   The metadata.
   */
  public function setMetadata($metadata) {

    if (!empty($metadata) && is_array($metadata)) {
      $this->metadata = $metadata;
    }
  }

  /**
   * Get the descriptor.
   *
   * @return mixed
   *   The descriptor.
   */
  public function getDescriptor() {
    return $this->descriptor;
  }

  /**
   * Set the descriptor.
   *
   * @param mixed $descriptor
   *   The descriptor.
   */
  public function setDescriptor(
    \com\checkout\Apiservices\Sharedmodels\Descriptor $descriptor
  ) {
    $this->descriptor = $descriptor;
  }
}
