<div class="checkout-help-page">
  <div class="pane">
    <div class="header">
      <img src="https://www.checkout.com/wp-content/uploads/2017/03/Logo.png" alt="Checkout.com" />
    </div>
    <div style="padding:20px;">
      <h3>A streamlined payment solution</h3>
      <p class="subtitle">Our solution does the hard work for you, from the moment your customer enters their payment details, to the instant
        you receive money in your account.</p>
      <img src="https://www.checkout.com/wp-content/uploads/2017/03/03.png" alt="">

    </div>

  </div>

  <div class="pane">
    <div class="header">
      <h2>Get more information</h2>
    </div>
    <div style="padding:50px 20px 20px 20px; height: 240px;">
      <div class="column">
        <img src="https://docs.checkout.com/img/newspaper-icon.png" alt="documentation">
        <p>
          Find the Checkout.com documentation.
        </p>
        <a href="https://docs.checkout.com" target="_blank" class="footerbutton">docs.checkout.com</a>
      </div>
      <div class="column">
        <img src="https://docs.checkout.com/img/api-icon.png" alt="Ubercart documentation">
        <p>
          Specific documentation for the this Ubercart module can be found on GitHub.
        </p>
        <a href="https://github.com/checkout/checkout-ubercart-module/wiki" target="_blank" class="footerbutton">GitHub wiki</a>
      </div>
      <div class="column">
        <img src="https://docs.checkout.com/img/newspaper-icon.png" alt="documentation">
        <p>
          If you found an issue, bug, or have a feature request, then you can submit them on GitHub.
        </p>
        <a href="https://github.com/checkout/checkout-ubercart-module/issues" target="_blank" class="footerbutton">GitHub issues</a>
      </div>
      <div class="column">
        <img src="https://docs.checkout.com/img/newspaper-icon.png" alt="documentation">
        <p>
          If you need assistance, feel free to drop us an email.
        </p>
        <a href="mailto:integration@checkout.com" target="_blank" class="footerbutton">integration@checkout.com</a>
      </div>
    </div>

  </div>
</div>