<p>
  Find the Checkout.com documentation on 
    <a href="https://docs.checkout.com" target="_blank"> 
      docs.checkout.com
    </a>.
</p>
<p>
  Specific documentation for the this Ubercart module can be found on 
  <a href="https://github.com/checkout/checkout-ubercart-module/wiki" target="_blank"> 
    GitHub wiki
  </a>.
</p>
<p>
  If you found an issue, bug, or have a feature request, then you can submit them on 
  <a href="https://github.com/checkout/checkout-ubercart-module/issues" target="_blank"> 
    GitHub issues
  </a>.
</p>
<p>
If you need assistance, feel free to drop us an email on
  <a href="mailto:integration@checkout.com" target="_blank"> 
    integration@checkout.com
  </a>.
</p>